# Generated by Django 4.2.1 on 2023-05-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('variable', 'Variable'), ('variation', 'Variation')], max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('images', models.CharField(max_length=10000)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('parent', models.CharField(default='', max_length=100)),
                ('id_product', models.CharField(max_length=100)),
                ('id_variant', models.CharField(max_length=100)),
            ],
        ),
    ]
