# Generated by Django 4.2.1 on 2023-05-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('variable', 'Variable'), ('variation', 'Variation'), ('simple', 'Simple')], max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('images', models.CharField(max_length=10000)),
                ('attribute_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_1_values', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_2_values', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_3_values', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_4_values', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_5_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_5_values', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('color_hex', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(default=0)),
                ('inventory_quantity', models.CharField(max_length=100)),
                ('parent', models.CharField(default='', max_length=100)),
                ('id_product', models.CharField(max_length=100)),
                ('id_variant', models.CharField(max_length=100)),
                ('update_shopify', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
