# Generated by Django 4.2.1 on 2023-05-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_product', '0002_product_color_hex_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_shopify',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
